# Generated by Django 5.2.13 on 2026-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_subscription_last_processed_at_subscriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delivery_day',
            field=models.CharField(choices=[('MONDAY', 'Lunes'), ('TUESDAY', 'Martes'), ('WEDNESDAY', 'Miércoles'), ('THURSDAY', 'Jueves'), ('FRIDAY', 'Viernes'), ('SATURDAY', 'Sábado'), ('SUNDAY', 'Domingo')], default='MONDAY', max_length=10),
        ),
    ]
