# Generated by Django 5.2.13 on 2026-05-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producto_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='verification_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
