# Generated by Django 5.2.13 on 2026-05-03 21:04

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producto_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.rename_product_image),
        ),
    ]
