# Generated by Django 5.2.13 on 2026-05-03 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_direccion_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_email', models.CharField(default='BIENVENIDA', max_length=50)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
