# Generated by Django 5.2.13 on 2026-05-16 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('address_line', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('address_type', models.CharField(choices=[('ENTREGA', 'Entrega'), ('RECOGIDA', 'Recogida')], default='ENTREGA', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10)),
                ('font_size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Grande'), ('x-large', 'Muy grande')], default='normal', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
