/**
 * Mapeo de provincias de España a una lista de ciudades para puntos de recogida.
 * Se incluyen 3 ciudades por cada una de las 52 provincias.
 */
export const CIUDADES_POR_PROVINCIA: { [key: string]: string[] } = {
  'Álava': ['Vitoria-Gasteiz', 'Llodio', 'Amurrio'],
  'Albacete': ['Albacete', 'Hellín', 'Villarrobledo'],
  'Alicante': ['Alicante', 'Elche', 'Torrevieja'],
  'Almería': ['Almería', 'Roquetas de Mar', 'El Ejido'],
  'Asturias': ['Oviedo', 'Gijón', 'Avilés'],
  'Ávila': ['Ávila', 'Arévalo', 'Arenas de San Pedro'],
  'Badajoz': ['Badajoz', 'Mérida', 'Don Benito'],
  'Barcelona': ['Barcelona', 'L\'Hospitalet de Llobregat', 'Badalona'],
  'Bizkaia': ['Bilbao', 'Barakaldo', 'Getxo'],
  'Burgos': ['Burgos', 'Miranda de Ebro', 'Aranda de Duero'],
  'Cáceres': ['Cáceres', 'Plasencia', 'Navalmoral de la Mata'],
  'Cádiz': ['Cádiz', 'Jerez de la Frontera', 'Algeciras'],
  'Cantabria': ['Santander', 'Torrelavega', 'Castro-Urdiales'],
  'Castellón': ['Castellón de la Plana', 'Vila-real', 'Burriana'],
  'Ceuta': ['Ceuta Centro', 'Puerto de Ceuta', 'Benalup'],
  'Ciudad Real': ['Ciudad Real', 'Puertollano', 'Tomelloso'],
  'Córdoba': ['Córdoba', 'Lucena', 'Puente Genil'],
  'A Coruña': ['A Coruña', 'Santiago de Compostela', 'Ferrol'],
  'Cuenca': ['Cuenca', 'Tarancón', 'Quintanar del Rey'],
  'Girona': ['Girona', 'Figueres', 'Blanes'],
  'Granada': ['Granada', 'Motril', 'Almuñécar'],
  'Guadalajara': ['Guadalajara', 'Azuqueca de Henares', 'Alovera'],
  'Gipuzkoa': ['Donostia-San Sebastián', 'Irún', 'Errenteria'],
  'Huelva': ['Huelva', 'Lepe', 'Almonte'],
  'Huesca': ['Huesca', 'Barbastro', 'Monzón'],
  'Illes Balears': ['Palma', 'Calvià', 'Ibiza'],
  'Jaén': ['Jaén', 'Linares', 'Andújar'],
  'León': ['León', 'Ponferrada', 'San Andrés del Rabanedo'],
  'Lleida': ['Lleida', 'Tàrrega', 'Balaguer'],
  'La Rioja': ['Logroño', 'Calahorra', 'Arnedo'],
  'Lugo': ['Lugo', 'Monforte de Lemos', 'Viveiro'],
  'Madrid': ['Madrid', 'Móstoles', 'Alcalá de Henares'],
  'Málaga': ['Málaga', 'Marbella', 'Vélez-Málaga'],
  'Melilla': ['Melilla Centro', 'Puerto de Melilla', 'Real de la Feria'],
  'Murcia': ['Murcia', 'Cartagena', 'Lorca'],
  'Navarra': ['Pamplona', 'Tudela', 'Barañáin'],
  'Ourense': ['Ourense', 'O Carballiño', 'Verín'],
  'Palencia': ['Palencia', 'Aguilar de Campoo', 'Guardo'],
  'Las Palmas': ['Las Palmas de Gran Canaria', 'Telde', 'Santa Lucía de Tirajana'],
  'Pontevedra': ['Vigo', 'Pontevedra', 'Vilagarcía de Arousa'],
  'Salamanca': ['Salamanca', 'Béjar', 'Ciudad Rodrigo'],
  'Santa Cruz de Tenerife': ['Santa Cruz de Tenerife', 'San Cristóbal de La Laguna', 'Arona'],
  'Segovia': ['Segovia', 'Cuéllar', 'El Espinar'],
  'Sevilla': ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra'],
  'Soria': ['Soria', 'Almazán', 'El Burgo de Osma'],
  'Tarragona': ['Tarragona', 'Reus', 'Tortosa'],
  'Teruel': ['Teruel', 'Alcañiz', 'Andorra'],
  'Toledo': ['Toledo', 'Talavera de la Reina', 'Illescas'],
  'Valencia': ['Valencia', 'Torrent', 'Gandia'],
  'Valladolid': ['Valladolid', 'Laguna de Duero', 'Medina del Campo'],
  'Zamora': ['Zamora', 'Benavente', 'Toro'],
  'Zaragoza': ['Zaragoza', 'Calatayud', 'Utebo'],
};
